name: go-test
on:
  push:
    paths-ignore: 
      - 'go.mod'
  pull_request:
    paths-ignore: 
      - 'go.mod'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set-up-go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: check-version
      run: go version
    - name: build
      run: go build -v ./...
    - name: test
      run: go test -v ./...
